version: '3.1'
services:
  mongohost:
    image: mongo:4 
    restart: always
    container_name: mongodb
    volumes:
      - ./dbdata:/data/db
    ports:
      - "27017:27017"

  restapi:
    build: .
    restart: always
    container_name: mongodbapi
    ports:
      - "5000:5098"
    depends_on:
      - mongohost
